#!/bin/bash
###
 # date:2022/2/11
 # @HIDS deployment(V1.1) ---dracula
###


#安装HIDS
function install_HIDS(){
  export WAZUH_AGENT_NAME=$(hostname)
  export WAZUH_REGISTRATION_PASSWORD='sgi4011pfj5rfjdkajf54q35we'
  sudo yum remove -y wazuh-agent; sudo rm -rf /var/ossec/ >/dev/null >&1
  ping -c1 wzlan-agent.cg.xxx &> /dev/null
  PINGresult=$?
  if [ $PINGresult -eq 0 ];then
    export WAZUH_MANAGER='wzlan-agent.cg.xxx'
    yum -y install https://packages.wazuh.com/4.x/yum/wazuh-agent-4.2.5-1.x86_64.rpm >/dev/null >&1
  else
    export WAZUH_MANAGER='wz-agent.cg.xxx'
    yum -y install https://packages.wazuh.com/4.x/yum/wazuh-agent-4.2.5-1.x86_64.rpm >/dev/null >&1
  fi
  yum -y install wget curl psmisc sshpass >/dev/null >&1
  rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  systemctl enable wazuh-agent >/dev/null >&1
  mkdir -p /var/ossec/wodles/oscap >/dev/null >&1
  cd /var/ossec/wodles/oscap/;sudo yum -y install openscap-scanner unzip >/dev/null >&1
  wget -c https://raw.githubusercontent.com/draculahaha/openscap/main/oscap.py >/dev/null >&1
  wget -c https://raw.githubusercontent.com/draculahaha/openscap/main/template_oval.xsl >/dev/null >&1
  wget -c https://raw.githubusercontent.com/draculahaha/openscap/main/template_xccdf.xsl >/dev/null >&1
  curl -LJO https://github.com/ComplianceAsCode/content/releases/download/v0.1.54/scap-security-guide-0.1.54.zip >/dev/null >&1
  unzip -jn scap-security-guide-0.1.54.zip -d content >/dev/null >&1
  chmod +x oscap.py >/dev/null >&1
  yum -y install yum-utils >/dev/null >&1
  curl -L https://pkg.osquery.io/rpm/GPG | tee /etc/pki/rpm-gpg/RPM-GPG-KEY-osquery >/dev/null >&1
  yum-config-manager --add-repo https://pkg.osquery.io/rpm/osquery-s3-rpm.repo >/dev/null >&1
  yum-config-manager --enable osquery-s3-rpm >/dev/null >&1
  yum -y install osquery >/dev/null >&1
  echo "CnsKICAgICJvcHRpb25zIjogewogICAgICAgICJjb25maWdfcGx1Z2luIjogImZpbGVzeXN0ZW0iLAogICAgICAgICJsb2dnZXJfcGx1Z2luIjogImZpbGVzeXN0ZW0iLAogICAgICAgICJ1dGMiOiAidHJ1ZSIKICAgIH0sCgoJInNjaGVkdWxlIjogewogICAgICAgICJzeXN0ZW1faW5mbyI6IHsKICAgICAgICAicXVlcnkiOiAiU0VMRUNUIGhvc3RuYW1lLCBjcHVfYnJhbmQsIHBoeXNpY2FsX21lbW9yeSBGUk9NIHN5c3RlbV9pbmZvOyIsCiAgICAgICAgImludGVydmFsIjogMzYwMAogICAgICAgIH0sCiAgICAgICAgImJlaGF2aW9yYWxfcmV2ZXJzZV9zaGVsbCI6IHsKICAgICAgICAicXVlcnkiIDogIlNFTEVDVCBESVNUSU5DVChwcm9jZXNzZXMucGlkKSwgcHJvY2Vzc2VzLnBhcmVudCwgcHJvY2Vzc2VzLm5hbWUsIHByb2Nlc3Nlcy5wYXRoLCBwcm9jZXNzZXMuY21kbGluZSwgcHJvY2Vzc2VzLmN3ZCwgcHJvY2Vzc2VzLnJvb3QsIHByb2Nlc3Nlcy51aWQsIHByb2Nlc3Nlcy5naWQsIHByb2Nlc3Nlcy5zdGFydF90aW1lLCBwcm9jZXNzX29wZW5fc29ja2V0cy5yZW1vdGVfYWRkcmVzcywgcHJvY2Vzc19vcGVuX3NvY2tldHMucmVtb3RlX3BvcnQsIChTRUxFQ1QgY21kbGluZSBGUk9NIHByb2Nlc3NlcyBBUyBwYXJlbnRfY21kbGluZSBXSEVSRSBwaWQ9cHJvY2Vzc2VzLnBhcmVudCkgQVMgcGFyZW50X2NtZGxpbmUgRlJPTSBwcm9jZXNzZXMgSk9JTiBwcm9jZXNzX29wZW5fc29ja2V0cyBVU0lORyAocGlkKSBMRUZUIE9VVEVSIEpPSU4gcHJvY2Vzc19vcGVuX2ZpbGVzIE9OIHByb2Nlc3Nlcy5waWQgPSBwcm9jZXNzX29wZW5fZmlsZXMucGlkIFdIRVJFIChuYW1lPSdzaCcgT1IgbmFtZT0nYmFzaCcgT1IgbmFtZT0nbmMnKSBBTkQgcmVtb3RlX2FkZHJlc3MgTk9UIElOICgnMC4wLjAuMCcsICc6OicsICcnKTsiLAogICAgICAgICJpbnRlcnZhbCIgOiAxMCwKICAgICAgICAiZGVzY3JpcHRpb24iIDogIkZpbmQgc2hlbGwgcHJvY2Vzc2VzIHRoYXQgaGF2ZSBvcGVuZWQgc29ja2V0cyIKICAgICAgICB9LAogICAgICAgICJoaWdoX2xvYWRfYXZlcmFnZSI6IHsKICAgICAgICAicXVlcnkiOiAiU0VMRUNUIHBlcmlvZCwgYXZlcmFnZSwgJzcwJScgQVMgJ3RocmVzaG9sZCcgRlJPTSBsb2FkX2F2ZXJhZ2UgV0hFUkUgcGVyaW9kID0gJzE1bScgQU5EIGF2ZXJhZ2UgPiAnMC43JzsiLAogICAgICAgICJpbnRlcnZhbCI6IDkwMCwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiUmVwb3J0IGlmIGxvYWQgY2hhcmdlIGlzIG92ZXIgNzAgcGVyY2VudC4iCiAgICAgICAgfSwKICAgICAgICAibG93X2ZyZWVfbWVtb3J5IjogewogICAgICAgICJxdWVyeSI6ICJTRUxFQ1QgbWVtb3J5X3RvdGFsLCBtZW1vcnlfZnJlZSwgQ0FTVChtZW1vcnlfZnJlZSBBUyByZWFsKSAvIG1lbW9yeV90b3RhbCBBUyBtZW1vcnlfZnJlZV9wZXJjLCAnMTAlJyBBUyB0aHJlc2hvbGQgRlJPTSBtZW1vcnlfaW5mbyBXSEVSRSBtZW1vcnlfZnJlZV9wZXJjIDwgMC4xOyIsCiAgICAgICAgImludGVydmFsIjogMTgwMCwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiRnJlZSBSQU0gaXMgdW5kZXIgMTAlLiIKICAgICAgICB9LAogICAgICAgIC8vInNoZWxsX2hpc3RvcnkiOiB7CiAgICAgICAgLy8icXVlcnkiOiAic2VsZWN0IHVzci51c2VybmFtZSwgc2h0LmNvbW1hbmQsIHNodC5oaXN0b3J5X2ZpbGUgZnJvbSBzaGVsbF9oaXN0b3J5IHNodCBKT0lOIHVzZXJzIHVzciBPTiBzaHQudWlkID0gdXNyLnVpZCBXSEVSRSBzaHQudWlkIElOIChTRUxFQ1QgdWlkIGZyb20gdXNlcnMpOyIsCiAgICAgICAgLy8iaW50ZXJ2YWwiOiAzNjAwLAogICAgICAgIC8vImRlc2NyaXB0aW9uIjogIkxpc3Qgc2hlbGxfaGlzdG9yeSBmb3IgZWFjaCB1c2VycyBvbiB0aGUgc3lzdGVtIiwKICAgICAgICAvLyJyZW1vdmVkIjogZmFsc2UKICAgICAgICAvL30sCiAgICAgICAgImxpbnV4X3VzZXJzIjogewogICAgICAgICJxdWVyeSI6ICJzZWxlY3QgKiBmcm9tIHVzZXJzOyIsCiAgICAgICAgImludGVydmFsIjogMzYwMCwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiTGlzdHMgYWxsIGNyZWF0ZSBhbmQgZGVsZXRlZCBhY2NvdW50IgogICAgICAgIH0sCiAgICAgICAgImxpbnV4X2xvZ2dlZF91c2VycyI6IHsKICAgICAgICAicXVlcnkiOiAic2VsZWN0IGRhdGV0aW1lKHRpbWUsJ3VuaXhlcG9jaCcsJ1VUQycpIGFzIHRpbWVfdXRjLGhvc3QsdXNlcix0dHkscGlkLHR5cGUgZnJvbSBsb2dnZWRfaW5fdXNlcnM7IiwKICAgICAgICAiaW50ZXJ2YWwiOiAzNjAwLAogICAgICAgICJkZXNjcmlwdGlvbiI6ICJMaXN0cyBhbGwgbG9nZ2VkIGluIHVzZXJzIgogICAgICAgIH0sCiAgICAgICAgImxpbnV4X2xhc3RfbG9nZ2VkX3VzZXJzIjogewogICAgICAgICJxdWVyeSI6ICJzZWxlY3QgZGF0ZXRpbWUodGltZSwndW5peGVwb2NoJywnVVRDJykgYXMgdGltZV91dGMsaG9zdCx1c2VybmFtZSx0dHkscGlkLHR5cGUgZnJvbSBsYXN0OyIsCiAgICAgICAgImludGVydmFsIjogMzYwMCwKICAgICAgICAiZGVzY3JpcHRpb24iOiAiTGlzdHMgbGFzdCBsb2dnZWQgaW4gdXNlcnMiCiAgICAgICAgfSwKICAgICAgICAibG9jYWxfam9iX3NjaGVkdWxpbmciOiB7CiAgICAgICAgInF1ZXJ5IjogInNlbGVjdCBjb21tYW5kLCBwYXRoIGZyb20gY3JvbnRhYjsiLAogICAgICAgICJpbnRlcnZhbCI6IDM2MDAsCiAgICAgICAgImRlc2NyaXB0aW9uIjogIkxpc3QgTG9jYWwgam9iIHNjaGVkdWxpbmcgd2l0aCBDcm9uIgogICAgICAgIH0sCiAgICAgICAgImxpbnV4X3Byb2Nlc3NfbGlzdGVuaW5nX2xvcnQiOiB7CiAgICAgICAgInF1ZXJ5IjogInNlbGVjdCBwLm5hbWUsIHAucGF0aCwgbHAucG9ydCwgbHAuYWRkcmVzcywgbHAucHJvdG9jb2wgIGZyb20gbGlzdGVuaW5nX3BvcnRzIGxwIExFRlQgSk9JTiBwcm9jZXNzZXMgcCBPTiBscC5waWQgPSBwLnBpZCBXSEVSRSBscC5wb3J0ICE9IDAgQU5EIHAubmFtZSAhPSAnJzsiLAogICAgICAgICJpbnRlcnZhbCI6IDM2MDAsCiAgICAgICAgImRlc2NyaXB0aW9uIjogIlJldHVybnMgdGhlIExpc3RlbmluZyBwb3J0IExpc3QiLAogICAgICAgICJyZW1vdmVkIjogZmFsc2UKICAgICAgICB9LAogICAgICAgICJsaW51eF9wcm9jZXNzX29wZW5fc29ja2V0cyI6IHsKICAgICAgICAicXVlcnkiOiAic2VsZWN0IERJU1RJTkNUIHAubmFtZSwgcC5wYXRoLCBwb3MucmVtb3RlX2FkZHJlc3MsIHBvcy5yZW1vdGVfcG9ydCBmcm9tIHByb2Nlc3Nfb3Blbl9zb2NrZXRzIHBvcyBMRUZUIEpPSU4gcHJvY2Vzc2VzIHAgT04gcG9zLnBpZCA9IHAucGlkIFdIRVJFIHBvcy5yZW1vdGVfcG9ydCAhPSAwIEFORCBwLm5hbWUgIT0gJyc7IiwKICAgICAgICAiaW50ZXJ2YWwiOiAzNjAwLAogICAgICAgICJkZXNjcmlwdGlvbiI6ICJSZXR1cm5zIHRoZSBuZXR3b3JrIGNvbm5lY3Rpb25zIGZyb20gc3lzdGVtIHByb2Nlc3NlcyIsCiAgICAgICAgInJlbW92ZWQiOiBmYWxzZQogICAgICAgIH0sCiAgICAgICAgImxpbnV4X3NoZWxsX2NoZWNrIjogewogICAgICAgICJxdWVyeSI6ICJTRUxFQ1QgRElTVElOQ1QocHJvY2Vzc2VzLnBpZCkscHJvY2Vzc2VzLnBhcmVudCxwcm9jZXNzZXMubmFtZSxwcm9jZXNzZXMucGF0aCxwcm9jZXNzZXMuY21kbGluZSxwcm9jZXNzZXMuY3dkLHByb2Nlc3Nlcy5yb290LHByb2Nlc3Nlcy51aWQscHJvY2Vzc2VzLmdpZCxwcm9jZXNzZXMuc3RhcnRfdGltZSxwcm9jZXNzX29wZW5fc29ja2V0cy5yZW1vdGVfYWRkcmVzcyxwcm9jZXNzX29wZW5fc29ja2V0cy5yZW1vdGVfcG9ydCwoU0VMRUNUIGNtZGxpbmUgRlJPTSBwcm9jZXNzZXMgQVMgcGFyZW50X2NtZGxpbmUgV0hFUkUgcGlkID0gcHJvY2Vzc2VzLnBhcmVudCkgQVMgcGFyZW50X2NtZGxpbmUgRlJPTSBwcm9jZXNzZXMgSk9JTiBwcm9jZXNzX29wZW5fc29ja2V0cyBVU0lORyhwaWQpIExFRlQgT1VURVIgSk9JTiBwcm9jZXNzX29wZW5fZmlsZXMgT04gcHJvY2Vzc2VzLnBpZCA9IHByb2Nlc3Nfb3Blbl9maWxlcy5waWQgV0hFUkUgKG5hbWUgPSAnc2gnIE9SIG5hbWUgPSAnYmFzaCcpIEFORCBwcm9jZXNzX29wZW5fZmlsZXMucGlkIElTIE5VTEw7IiwKICAgICAgICAiaW50ZXJ2YWwiOiAzNjAwLAogICAgICAgICJkZXNjcmlwdGlvbiI6ICJDaGVjayBSZXR1cm5zIHBvc3NpYmxlIFJldmVyc2UgU2hlbGxzIG9uIHN5c3RlbSBwcm9jZXNzZXMiLAogICAgICAgICJyZW1vdmVkIjogZmFsc2UKICAgICAgICB9CiAgICB9LAoKICAgICJwYWNrcyI6IHsKICAgICAgICAvLyAib3NxdWVyeS1tb25pdG9yaW5nIjogIi91c3Ivc2hhcmUvb3NxdWVyeS9wYWNrcy9vc3F1ZXJ5LW1vbml0b3JpbmcuY29uZiIsCiAgICAgICAgLy8gImluY2lkZW50LXJlc3BvbnNlIjogIi91c3Ivc2hhcmUvb3NxdWVyeS9wYWNrcy9pbmNpZGVudC1yZXNwb25zZS5jb25mIiwKICAgICAgICAvLyAiaXQtY29tcGxpYW5jZSI6ICIvdXNyL3NoYXJlL29zcXVlcnkvcGFja3MvaXQtY29tcGxpYW5jZS5jb25mIiwKICAgICAgICAvLyAidnVsbi1tYW5hZ2VtZW50IjogIi91c3Ivc2hhcmUvb3NxdWVyeS9wYWNrcy92dWxuLW1hbmFnZW1lbnQuY29uZiIsCiAgICAgICAgLy8gImhhcmR3YXJlLW1vbml0b3JpbmciOiAiL3Vzci9zaGFyZS9vc3F1ZXJ5L3BhY2tzL2hhcmR3YXJlLW1vbml0b3JpbmcuY29uZiIsCiAgICAgICAgIm9zc2VjLXJvb3RraXQiOiAiL3Vzci9zaGFyZS9vc3F1ZXJ5L3BhY2tzL29zc2VjLXJvb3RraXQuY29uZiIKICAgIH0KfQ==" | base64 -d > /etc/osquery/osquery.conf
  systemctl disable osqueryd >/dev/null >&1
  systemctl start osqueryd >/dev/null >&1
  systemctl stop osqueryd >/dev/null >&1
  systemctl restart wazuh-agent >/dev/null >&1
  if [ $PINGresult -eq 0 ];then
    /var/ossec/bin/agent-auth -m wzlan-agent.cg.xxx -P "sgi4011pfj5rfjdkajf54q35we" >/dev/null >&1
    systemctl restart wazuh-agent >/dev/null >&1
  else
    /var/ossec/bin/agent-auth -m wz-agent.cg.xxx -P "sgi4011pfj5rfjdkajf54q35we" >/dev/null >&1
    systemctl restart wazuh-agent >/dev/null >&1
  fi
}



#main函数入口函数
function main() {
  #安装HIDS
  install_HIDS
}
main

